# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = '<i class="fas fa-home"></i>'
  url = "/"
  weight = 5

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  name = "Team"
  url = "people"
  weight = 59

[[main]] 
  name = "Data"
  url = "data/"
  weight = 34

[[main]]
  identifier = "reports"
  name = "Reports"
#  url = "reports/"
  weight = 35

[[main]]
  name = "Monthly reports"
  parent = "reports"
  url = "reports/monthly/"
  weight = 36

[[main]]
  name = "Specialised reports"
  parent = "reports"
  url = "reports/specialised/"
  weight = 37

[[main]]
  name = "Dashboard"
  url = "https://asavagar.shinyapps.io/UKFirmCreation/"
  weight = 40

[[main]]
  name = "Publications"
  url = "publication"
  weight = 50

[[main]]
  name = "Contact"
  url = "contact"
  weight = 60


